DROP TABLE IF EXISTS TBL_CLASSPAGES;

CREATE TABLE TBL_CLASSPAGES(
    id INT AUTO_INCREMENT PRIMARY KEY,
    teacher_first_name VARCHAR(30) NOT NULL,
    teacher_last_name VARCHAR(30) NOT NULL,
    class_name VARCHAR(50) NOT NULL
);